language: cpp
sudo: required
dist: trusty
compiler: g++
install: true
before_script:
    - g++ --version
script:
    - cd A8/AngryWords && rm -f Makefile
    - qmake
    - make clean
    - make
    - cd ../AngryWordsServer && rm -f Makefile
    - qmake
    - make clean
    - make
addons:
  apt:
    packages:
    - g++-4.8
    - gcc-4.8
    - libsfml-dev
    - qtbase5-dev
    - qtdeclarative5-dev
    - qttools5-dev-tools
    - qt5-default
    - qt5-qmake
    - libasound2-dev
    - libgstreamer0.10-dev
    - libgstreamer-plugins-base0.10-dev
    - libqt5opengl5-dev
    - libqt5sql5-mysql
    - libqt5sql5-sqlite
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
 
